---
title: "Demo with Flexdashboard and D3po"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#ffffff"
      fg: "#000000" 
      primary: "#273661"
      base_font:
        google: Source Sans 3 
      code_font:
        google: Source Code Pro
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Average Household Expenditure by State in India (2023-24, PLFS)

```{r, echo = FALSE, warning=FALSE, message=FALSE}
if (!require("d3po")) install.packages("d3po", repos = "https://pachadotdev.r-universe.dev")
if (!require("dplyr")) install.packages("dplyr", repos = "https://cran.r-project.org")
if (!require("duckdb")) install.packages("duckdb", repos = "https://cran.r-project.org")
if (!require("sf")) install.packages("sf", repos = "https://cran.r-project.org")

library(d3po)
library(dplyr)
library(duckdb)
library(sf)

fout <- "mean_expenditure.rds"

if (file.exists(fout)) {
  mean_expenditure <- readRDS(fout)
  map_india <- d3po::maps$asia$india
  labels_india <- map_ids(d3po::maps$asia$india)
} else {
  library(plfs)

  con <- dbConnect(duckdb(), plfs_file_path())

  # dbListTables(con)

  # average household expenditure by state

  mean_expenditure <- tbl(con, "2023-24-hhv1") %>%
    group_by(state_code = state_hhv1) %>%
    summarise(avg_expenditure = round(mean(b3q5pt1_hhv1, na.rm = TRUE), 0)) %>%
    collect()

  dbDisconnect(con, shutdown = TRUE)

  # merge data with map of India states

  india_states <- readRDS("india_states_map.rds")

  mean_expenditure <- mean_expenditure %>%
    left_join(
      india_states %>%
        as.data.frame() %>%
        select(-geometry)
    )

  map_india <- d3po::maps$asia$india
  labels_india <- map_ids(d3po::maps$asia$india)

  mean_expenditure <- mean_expenditure %>%
    # state_name -> name
    # Uttarakhand -> Uttaranchal
    # Dadra and Nagar Haveli and Daman and Diu -> Daman and Diu
    # Odisha -> Orissa
    # Telangana -> Andhra Pradesh ?
    # Ladakh ->
    # Andaman and Nicobar -> ?
    mutate(
      state_name = case_when(
        state_name == "Uttarakhand" ~ "Uttaranchal",
        state_name == "Dadra and Nagar Haveli and Daman and Diu" ~ "Daman and Diu",
        state_name == "Odisha" ~ "Orissa",
        state_name == "Telangana" ~ "Andhra Pradesh",
        state_name == "Ladakh" ~ "Jammu and Kashmir",
        TRUE ~ state_name
      )
    ) %>%
    left_join(labels_india, by = c("state_name" = "name"))

  # add a color column with a gradient based on avg_expenditure
  mean_expenditure <- mean_expenditure %>%
    mutate(
      color = ifelse(
        is.na(avg_expenditure),
        "#e0e0e0",
        scales::col_numeric(
          palette = "YlOrRd",
          domain = range(mean_expenditure$avg_expenditure, na.rm = TRUE)
        )(avg_expenditure)
      )
    )

  saveRDS(mean_expenditure, fout)
}

# for light theme
axis_color <- "#000"
tooltip_color <- "#fff"

d3po(mean_expenditure) %>%
  po_geomap(daes(group = id, color = color, size = avg_expenditure, tooltip = state_name), map = map_india) %>%
  po_background("transparent") %>%
  po_theme(axis = axis_color, tooltips = tooltip_color)
```

### Average Manufacturing Days by State in India (2022-23, ASI)

```{r, echo = FALSE, warning=FALSE, message=FALSE}
fout <- "mean_manufacture.rds"

if (file.exists(fout)) {
  mean_expenditure <- readRDS(fout)
} else {
  library(asi)

  con <- dbConnect(duckdb(), asi_file_path())

  # dbListTables(con)

  # average household expenditure by state

  mean_manufacturing <- tbl(con, "2022-23-blkA") %>%
    group_by(state_code = a7) %>%
    summarise(mwdays = round(mean(mwdays, na.rm = TRUE), 0)) %>%
    collect()

  dbDisconnect(con, shutdown = TRUE)

  # merge data with map of India states

  india_states <- readRDS("india_states_map.rds")

  mean_manufacturing <- mean_manufacturing %>%
    left_join(
      india_states %>%
        as.data.frame() %>%
        select(-geometry)
    )

  map_india <- d3po::maps$asia$india
  labels_india <- map_ids(d3po::maps$asia$india)

  mean_manufacturing <- mean_manufacturing %>%
    # state_name -> name
    # Uttarakhand -> Uttaranchal
    # Dadra and Nagar Haveli and Daman and Diu -> Daman and Diu
    # Odisha -> Orissa
    # Telangana -> Andhra Pradesh ?
    # Ladakh ->
    # Andaman and Nicobar -> ?
    mutate(
      state_name = case_when(
        state_name == "Uttarakhand" ~ "Uttaranchal",
        state_name == "Dadra and Nagar Haveli and Daman and Diu" ~ "Daman and Diu",
        state_name == "Odisha" ~ "Orissa",
        state_name == "Telangana" ~ "Andhra Pradesh",
        state_name == "Ladakh" ~ "Jammu and Kashmir",
        TRUE ~ state_name
      )
    ) %>%
    left_join(labels_india, by = c("state_name" = "name"))

  # add a color column with a gradient based on avg_expenditure
  mean_manufacturing <- mean_manufacturing %>%
    mutate(
      color = ifelse(
        is.na(mwdays),
        "#e0e0e0",
        scales::col_numeric(
          palette = "YlOrRd",
          domain = range(mean_manufacturing$mwdays, na.rm = TRUE)
        )(mwdays)
      )
    )

  saveRDS(mean_manufacturing, fout)
}

# for light theme
axis_color <- "#000"
tooltip_color <- "#fff"

d3po(mean_manufacturing) %>%
  po_geomap(daes(group = id, color = color, size = mwdays, tooltip = state_name), map = map_india) %>%
  po_background("transparent") %>%
  po_theme(axis = axis_color, tooltips = tooltip_color)
```
